//! Управление Git-хуками для проектов (post-commit, post-merge, post-checkout).
//! Обеспечивает автоматическое инкрементальное обновление графа при фиксации изменений.

use std::fs;
use std::path::Path;
use anyhow::{bail, Context, Result};
use tracing::info;

/// Содержимое скрипта post-commit хука
pub fn generate_post_commit_hook(project_id: &str) -> String {
    format!(
        r#"#!/usr/bin/env sh
# Auto-generated by ob2h (OmnesBOT for Hermes)
# Automatically updates project AST graph on commit

if command -v ob2h >/dev/null 2>&1; then
    ob2h project scan --id "{project_id}" >/dev/null 2>&1 &
elif [ -f "./target/release/ob2h" ]; then
    ./target/release/ob2h project scan --id "{project_id}" >/dev/null 2>&1 &
elif [ -f "./target/release/ob2h.exe" ]; then
    ./target/release/ob2h.exe project scan --id "{project_id}" >/dev/null 2>&1 &
fi
"#
    )
}

/// Содержимое скрипта post-merge хука
pub fn generate_post_merge_hook(project_id: &str) -> String {
    format!(
        r#"#!/usr/bin/env sh
# Auto-generated by ob2h (OmnesBOT for Hermes)
# Automatically updates project AST graph on git pull/merge

if command -v ob2h >/dev/null 2>&1; then
    ob2h project scan --id "{project_id}" >/dev/null 2>&1 &
elif [ -f "./target/release/ob2h" ]; then
    ./target/release/ob2h project scan --id "{project_id}" >/dev/null 2>&1 &
elif [ -f "./target/release/ob2h.exe" ]; then
    ./target/release/ob2h.exe project scan --id "{project_id}" >/dev/null 2>&1 &
fi
"#
    )
}

/// Содержимое скрипта post-checkout хука
pub fn generate_post_checkout_hook(project_id: &str) -> String {
    format!(
        r#"#!/usr/bin/env sh
# Auto-generated by ob2h (OmnesBOT for Hermes)
# Updates active branch and triggers incremental scan on branch switch

BRANCH_FLAG=$3

if [ "$BRANCH_FLAG" = "1" ]; then
    if command -v ob2h >/dev/null 2>&1; then
        ob2h project scan --id "{project_id}" >/dev/null 2>&1 &
    elif [ -f "./target/release/ob2h" ]; then
        ./target/release/ob2h project scan --id "{project_id}" >/dev/null 2>&1 &
    elif [ -f "./target/release/ob2h.exe" ]; then
        ./target/release/ob2h.exe project scan --id "{project_id}" >/dev/null 2>&1 &
    fi
fi
"#
    )
}

/// Устанавливает git-хуки в .git/hooks репозитория
pub fn install_git_hooks(repo_root: &Path, project_id: &str) -> Result<Vec<String>> {
    let git_dir = repo_root.join(".git");
    if !git_dir.exists() {
        bail!("Каталог .git не найден в {}", repo_root.display());
    }

    let hooks_dir = git_dir.join("hooks");
    fs::create_dir_all(&hooks_dir).context("Не удалось создать каталог .git/hooks")?;

    let hooks = [
        ("post-commit", generate_post_commit_hook(project_id)),
        ("post-merge", generate_post_merge_hook(project_id)),
        ("post-checkout", generate_post_checkout_hook(project_id)),
    ];

    let mut installed = Vec::new();
    for (name, content) in &hooks {
        let hook_path = hooks_dir.join(name);
        fs::write(&hook_path, content)
            .with_context(|| format!("Не удалось записать хук {}", hook_path.display()))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&hook_path)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&hook_path, perms)?;
        }

        installed.push(name.to_string());
        info!("GitHook: установлен {}", hook_path.display());
    }

    Ok(installed)
}
